#! /bin/bash

function install() {
    sudo apt-get install -y $1 >/dev/null 2>&1 
}

programs="build-essential vim curl htop git make python-dev apache2 php php-mysql php-mysqlnd php-mdb2-driver-mysql lynx" 

echo "Installing web-server essentials... This will take some time..."

sudo apt-get update >/dev/null 2>&1 

echo "Starting to install extra programs"

for program in $programs
do 
    echo "Current package: $program" 
    install $program 
done 

echo "Symlinking /var/www folder to /vagrant folder..."

rm -rf /var/www
mkdir /var/www
ln -fs /vagrant /var/www/html

echo "All done! Access the webserver from 'http://localhost:8080', or execute 'vagrant ssh' to access the server." 