#! /bin/bash

function install() {
sudo apt-get install -y $1 >/dev/null 2>&1 
    }

programs="build-essential vim curl  htop git make python-dev apache2 php5 php5-mysql
php5-mysqlnd php-mdb2-driver-mysql mysql-libs" 

echo "Installing web-server essentials... "

sudo apt-get update >/dev/null 2>&1 

for program in $programs
do 
    echo "Current package: $program" 
    install $program 

done 

echo "Symlincing /www folder to /Vagrant folder..."

rm -rf /var/www
ln -fs /vagrant /var/www 

echo "All done! Access webserver from localhost:8080 or go 'vagrant ssh' to access the server." 
